package dev.vrba.secrethitler.engine;

public enum Phase {
    PRESIDENT_IS_SELECTING_CHANCELLOR,

    VOTING_FOR_THE_GOVERNMENT,

    PRESIDENT_IS_SELECTING_POLICY,
    CHANCELLOR_IS_SELECTING_POLICY,

    PRESIDENT_IS_APPROVING_VETO,

    PRESIDENT_IS_PEEKING_POLICIES,
    PRESIDENT_IS_SELECTING_PLAYER_FOR_LOYALTY_INVESTIGATION,
    PRESIDENT_IS_SELECTING_PLAYER_FOR_EXECUTION,
    PRESIDENT_IS_SELECTING_THE_NEXT_PRESIDENT,

    GAME_ENDED
}
